# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_access.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth_access.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61uth_access.proto\x12\x08\x61uthoriz\"2\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"<\n\rTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"h\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x12\n\nexpires_at\x18\x04 \x01(\x03\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\x97\x02\n\x0b\x41uthService\x12>\n\x08Register\x12\x19.authoriz.RegisterRequest\x1a\x17.authoriz.TokenResponse\x12\x38\n\x05Login\x12\x16.authoriz.LoginRequest\x1a\x17.authoriz.TokenResponse\x12<\n\x07Refresh\x12\x18.authoriz.RefreshRequest\x1a\x17.authoriz.TokenResponse\x12P\n\rValidateToken\x12\x1e.authoriz.ValidateTokenRequest\x1a\x1f.authoriz.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_access_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=31
  _globals['_REGISTERREQUEST']._serialized_end=81
  _globals['_LOGINREQUEST']._serialized_start=83
  _globals['_LOGINREQUEST']._serialized_end=130
  _globals['_REFRESHREQUEST']._serialized_start=132
  _globals['_REFRESHREQUEST']._serialized_end=171
  _globals['_TOKENRESPONSE']._serialized_start=173
  _globals['_TOKENRESPONSE']._serialized_end=233
  _globals['_VALIDATETOKENREQUEST']._serialized_start=235
  _globals['_VALIDATETOKENREQUEST']._serialized_end=272
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=274
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=378
  _globals['_AUTHSERVICE']._serialized_start=381
  _globals['_AUTHSERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
