# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"W\n\x14GenerateImageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0f\n\x07profile\x18\x04 \x01(\t\"|\n\x15GenerateImageResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x14\n\x0cresults_json\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\x03\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"D\n\x12ListHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"{\n\x10ImageHistoryItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x14\n\x0cresults_json\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"L\n\x13ListHistoryResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.image.ImageHistoryItem\x12\r\n\x05total\x18\x02 \x01(\x05\"1\n\x12\x44\x65leteImageRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"0\n\x13\x44\x65leteImageResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xe6\x01\n\x0cImageService\x12J\n\rGenerateImage\x12\x1b.image.GenerateImageRequest\x1a\x1c.image.GenerateImageResponse\x12\x44\n\x0bListHistory\x12\x19.image.ListHistoryRequest\x1a\x1a.image.ListHistoryResponse\x12\x44\n\x0b\x44\x65leteImage\x12\x19.image.DeleteImageRequest\x1a\x1a.image.DeleteImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEIMAGEREQUEST']._serialized_start=22
  _globals['_GENERATEIMAGEREQUEST']._serialized_end=109
  _globals['_GENERATEIMAGERESPONSE']._serialized_start=111
  _globals['_GENERATEIMAGERESPONSE']._serialized_end=235
  _globals['_LISTHISTORYREQUEST']._serialized_start=237
  _globals['_LISTHISTORYREQUEST']._serialized_end=305
  _globals['_IMAGEHISTORYITEM']._serialized_start=307
  _globals['_IMAGEHISTORYITEM']._serialized_end=430
  _globals['_LISTHISTORYRESPONSE']._serialized_start=432
  _globals['_LISTHISTORYRESPONSE']._serialized_end=508
  _globals['_DELETEIMAGEREQUEST']._serialized_start=510
  _globals['_DELETEIMAGEREQUEST']._serialized_end=559
  _globals['_DELETEIMAGERESPONSE']._serialized_start=561
  _globals['_DELETEIMAGERESPONSE']._serialized_end=609
  _globals['_IMAGESERVICE']._serialized_start=612
  _globals['_IMAGESERVICE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
